apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    
    [security]
    admin_user = admin
    admin_password = admin
    
    [paths]
    provisioning = /etc/grafana/provisioning
    
    [provisioning]
    dashboards = true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
  labels:
    app: grafana
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
  labels:
    app: grafana
data:
  k3s-overview.json: |
    {
      "dashboard": {
        "title": "K3s Cluster Overview",
        "tags": ["k3s", "kubernetes"],
        "timezone": "browser",
        "schemaVersion": 16,
        "version": 0,
        "refresh": "10s",
        "panels": [
          {
            "id": 1,
            "title": "CPU Usage",
            "type": "graph",
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0},
            "targets": [
              {
                "expr": "100 - (avg(rate(container_cpu_usage_seconds_total{name!=\"\", container_name!=\"POD\"}[5m])) by (pod_name) * 100)",
                "legendFormat": "{{pod_name}}",
                "refId": "A"
              }
            ],
            "yaxes": [
              {"format": "percent", "min": 0, "max": 100},
              {"format": "short"}
            ]
          },
          {
            "id": 2,
            "title": "Memory Usage",
            "type": "graph",
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0},
            "targets": [
              {
                "expr": "sum(container_memory_usage_bytes{name!=\"\", container_name!=\"POD\"}) by (pod_name) / 1024 / 1024",
                "legendFormat": "{{pod_name}}",
                "refId": "A"
              }
            ],
            "yaxes": [
              {"format": "mbytes"},
              {"format": "short"}
            ]
          },
          {
            "id": 3,
            "title": "Pod Status",
            "type": "table",
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 8},
            "targets": [
              {
                "expr": "kube_pod_status_phase",
                "format": "table",
                "refId": "A"
              }
            ]
          },
          {
            "id": 4,
            "title": "Node Status",
            "type": "stat",
            "gridPos": {"h": 4, "w": 8, "x": 0, "y": 16},
            "targets": [
              {
                "expr": "count(kube_node_info)",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "thresholds"},
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {"value": 0, "color": "red"},
                    {"value": 1, "color": "green"}
                  ]
                }
              }
            }
          },
          {
            "id": 5,
            "title": "Running Pods",
            "type": "stat",
            "gridPos": {"h": 4, "w": 8, "x": 8, "y": 16},
            "targets": [
              {
                "expr": "count(kube_pod_status_phase{phase=\"Running\"})",
                "refId": "A"
              }
            ]
          },
          {
            "id": 6,
            "title": "Network I/O",
            "type": "graph",
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 20},
            "targets": [
              {
                "expr": "rate(container_network_receive_bytes_total{name!=\"\"}[5m])",
                "legendFormat": "RX {{pod_name}}",
                "refId": "A"
              },
              {
                "expr": "rate(container_network_transmit_bytes_total{name!=\"\"}[5m])",
                "legendFormat": "TX {{pod_name}}",
                "refId": "B"
              }
            ],
            "yaxes": [
              {"format": "Bps"},
              {"format": "short"}
            ]
          }
        ]
      }
    }

