apiVersion: v1
kind: Service
metadata:
  name: hidden-params
  namespace: hidden-params
  labels:
    app: hidden-params
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30103
    protocol: TCP
    name: http
  selector:
    app: hidden-params

