apiVersion: v1
kind: Service
metadata:
  name: header-leak
  namespace: header-leak
  labels:
    app: header-leak
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30101
    protocol: TCP
    name: http
  selector:
    app: header-leak

