apiVersion: v1
kind: Service
metadata:
  name: secret-leak
  namespace: secret-leak
  labels:
    app: secret-leak
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30100
    protocol: TCP
    name: http
  selector:
    app: secret-leak

