apiVersion: v1
kind: Service
metadata:
  name: file-disclosure
  namespace: file-disclosure
  labels:
    app: file-disclosure
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30102
    protocol: TCP
    name: http
  selector:
    app: file-disclosure

